---
title: "day3"
date: "2024-12-05"
---

```{r library}
library(stringr)
library(readr)
```

```{r import}
# Set the file path
file_path <- "day3_input.txt"
# Read the file using readLines()
file_content <- readLines(file_path)
# Collapse the lines into a single string
file_string <- paste(file_content, collapse = "\n")
str <- toString(file_string)

# Set the file path
file_path <- "day3_test_input.txt"
# Read the file using readLines()
file_content <- readLines(file_path)
# Collapse the lines into a single string
file_string_test <- paste(file_content, collapse = "\n")
str_test <- toString(file_string_test)
```

```{r functions}

cond_discover <- function(input_str){
  output <- str_match_all(input_str,"mul\\(\\s*(.*?)\\s*\\)")
  output_do <- str_match_all(input_str,"do\\(\\)\\s*(.*?)\\s*don't\\(\\)")
  output_dont <- str_match_all(input_str,"don't\\(\\)\\s*(.*?)\\s*do\\(\\)")
  
  sol_do <- matrix(0, nrow = length(output_do[[1]][,1]), ncol = 1)
  sol_dont <- matrix(0, nrow = length(output_dont[[1]][,1]), ncol = 1)
  sol <- matrix(0, nrow = length(output[[1]][1:24,2]), ncol = 1)
  
  for (i in 1:length(output_dont[[1]][,1])) {
    muls <- mul_discover(output_dont[[1]][i,2])
    sol_dont[i] <- mullitover_calc(muls)
  }
  
  for (i in 1:length(output_dont[[1]][,1])) {
    muls <- mul_discover(output_dont[[1]][i,2])
    sol_do[i] <- mullitover_calc(muls)
  }

  total <- sum(sol)+sum(sol_do)
  
  return(sum(sol_dont))
}


mul_discover <- function(input_str){
  
  output <- str_match_all(input_str,"mul\\(\\s*(.*?)\\s*\\)")
  check_str <- c("m","u","l","\\(",",","\\)")
  num_let_par <- c("[:alnum:]",",","\\)","\\(")
  check_para_true <- c("[:digit:]",",")
  check_para_false <- c("[:alpha:]")
  check_punc_space <- c("[:punct:]","[:space:]")
  check_astx <- c("\\*")

  for (i in 1:length(output[[1]][,1])) {
    init_i <- output[[1]][i,1]
    test_i <- str_detect(init_i,num_let_par)
    
    
    init_p <- output[[1]][i,2]
    test_p_t <- str_detect(init_p,check_para_true)
    test_p_f <- str_detect(init_p,check_para_false)
    test_e <- str_detect(init_p,check_punc_space)
    
    
    if (sum(test_i) == 4 && sum(test_p_t) == 2 && sum(test_p_f) == 0){
      mul_test <- str_match_all(init_p,"mul\\(\\s*(.*?)\\s*,")
      
      if (length(mul_test[[1]]) == 0){
        if (sum(test_e) == 1){
          if (str_detect(init_p,check_astx) == TRUE){
            output[[1]][i,1] <- 0
            output[[1]][i,2] <- 0
          } else if (str_detect(init_p,check_astx) == FALSE){
            #do nothing
          }
        } else if (sum(test_e) != 1){
          output[[1]][i,1] <- 0
          output[[1]][i,2] <- 0
        }
      } else if (length(mul_test[[1]]) != 0){
        split_init <- str_extract_all(init_i, boundary("character"))
        split_init_1 <- split_init
        split_init_2 <- split_init
        
        split_init_1[[1]][length(split_init_1[[1]])] <- "*"
        split_init_2[[1]][1] <- "*"
        
        split_init_1 <- paste(split_init_1[[1]], collapse="")
        split_init_2 <- paste(split_init_2[[1]], collapse="")
        
        output1 <- str_match_all(split_init_1,"mul\\(\\s*(.*?)\\s*\\)")
        output2 <- str_match_all(split_init_2,"mul\\(\\s*(.*?)\\s*\\)")
      
        if (length(output1[[1]]) == 0 && length(output2[[1]]) == 0){
          output[[1]][i,1] <- 0
          output[[1]][i,2] <- 0
        } else if (length(output1[[1]]) == 0){
            output[[1]][i,1] <- output2[[1]][,1]
           } else if (length(output2[[1]]) == 0 ){
           output[[1]][i,1] <- output1[[1]][,1]
           }
      }
          
    } else if (sum(test_i) == 4 && sum(test_p_t) == 2 && sum(test_p_f) == 1) {
        split_init <- str_extract_all(init_i, boundary("character"))
        split_init_1 <- split_init
        split_init_2 <- split_init
        
        split_init_1[[1]][length(split_init_1[[1]])] <- "*"
        split_init_2[[1]][1] <- "*"
        
        split_init_1 <- paste(split_init_1[[1]], collapse="")
        split_init_2 <- paste(split_init_2[[1]], collapse="")
        
        output1 <- str_match_all(split_init_1,"mul\\(\\s*(.*?)\\s*\\)")
        output2 <- str_match_all(split_init_2,"mul\\(\\s*(.*?)\\s*\\)")
      
          if (length(output1[[1]]) == 0 && length(output2[[1]]) == 0){
            output[[1]][i,1] <- 0
             output[[1]][i,2] <- 0
          } else if (length(output1[[1]]) == 0){
             output[[1]][i,1] <- output2[[1]][,1]
             output[[1]][i,2] <- output2[[1]][,2]
           } else if (length(output2[[1]]) == 0){
             output[[1]][i,1] <- output1[[1]][,1]
             output[[1]][i,2] <- output1[[1]][,2]
           }
    } else if (sum(test_i) != 4 && sum(test_p_t) != 2 && sum(test_p_f) == 1){
        output[[1]][i,1] <- 0
        output[[1]][i,2] <- 0
    } 
  } 
   
  return(output)
}
  
  
mullitover_calc <- function(input){
    temp <- str_split(input[[1]][,2],",")
    
    sol <- matrix(0, nrow = length(temp), ncol = 1)
    
    for (i in 1:length(temp)) {
      nums <- parse_number(temp[[i]])
      if (length(nums) == 1){
        sol[i] <- 0
      } else if (length(nums) == 2){
        result <- nums[1]*nums[2]
        sol[i] <- result
      }
    }
    
    ans <- sum(sol) 
    return(ans)
  }


  


```

```{r main}
result_pt1 <- mullitover_calc(mul_discover(str)) 
result_pt1 # answer = 164730528

result_pt2 <- cond_discover(str)
result_pt2 # answer = 50691713 too low, 108299376 too high
```

```{r tests}

```