---
title: "day3"
date: "2024-12-05"
---

```{r library}
library(stringr)
library(readr)
library(sjmisc)
```

```{r import}
# Set the file path
file_path <- "day6_input.txt"
# Read the file using readLines()
file_content <- readLines(file_path)

# Set the file path
file_path_test <- "day6_test_input.txt"
# Read the file using readLines()
file_content_test <- readLines(file_path_test)


```

```{r functions}
#Part 1

input_map <- file_content

direction <- c("\\^","v","\\>","\\<")
wall <- c("#")
dist_pos <- 1
count <- 0
off_map_flag <- FALSE

find_guard_details <- function(input_map, direction, dist_pos){
  for (i in 1:length(direction)){
    find_guard_y <- str_match_all(input_map,direction[i])
    test <- which(lengths(find_guard_y)!=0)
    
    if (!is_empty(test)){
      y <- which(lengths(find_guard_y)!=0)
      row_y_split <- str_extract_all(input_map[y], boundary("character"))
      find_guard_x <- str_match_all(row_y_split[[1]],direction[i])
      x <- which(lengths(find_guard_x)!=0)
      if ( i == 1){
        dir <- "^" #up
      } else if ( i == 2){
        dir <- "v" #down
      } else if ( i == 3){
        dir <- ">" #right
      } else if ( i == 4){
        dir <- "<" #left
      }
    }
  }
 
 return(list(y_loc = y, x_loc = x, direction = dir, 
             dist_pos = dist_pos))
}

#Motion Up solver
motion_up <- function(guard_details_input, input_map, direction){
  motion <- c("Move","Stop")
  input_map_extract <- str_extract_all(input_map, boundary("character"))
  walls_along_route <- vector(mode = "list", length = guard_details_input$y_loc)
    
  for (i in 1:guard_details_input$y_loc){
    wall_x <- str_match_all(input_map_extract[[i]][guard_details_input$x_loc],wall)
      if (is_empty(wall_x)) {
          walls_along_route[[i]] <- "Move"
      } else if (!is_empty(wall_x)){
          walls_along_route[[i]] <- "Stop"
      }
    }

  find_all_stops <- str_match_all(walls_along_route,"Stop")
  
  if (is_empty(find_all_stops)){

      for (i in 1:(guard_details_input$y_loc)){
        input_map_extract[[i]][guard_details_input$x_loc] <- "X"
      }
      
      for (i in 1:length(input_map_extract)){
        input_map[[i]] <- paste(input_map_extract[[i]], collapse="")
      }
    
      return(list(dist_pos = (guard_details_input$dist_pos+length(find_all_stops)),
                  input_map = input_map, flag = TRUE))
      break
  } else if (!is_empty(find_all_stops)){
  
      first_stop <- max(which(lengths(find_all_stops)!=0))
      total_moves_up <- guard_details_input$y_loc - 1 - first_stop
      new_y_loc <- guard_details_input$y_loc - total_moves_up
      
      #input_map_extract[[guard_details_input$y_loc]][guard_details_input$x_loc] <- "X"
      input_map_extract[[new_y_loc]][guard_details_input$x_loc] <- ">"
      for (i in (new_y_loc+1):(guard_details_input$y_loc)){
        input_map_extract[[i]][guard_details_input$x_loc] <- "X"
      }
    
      for (i in 1:length(input_map_extract)){
        input_map[[i]] <- paste(input_map_extract[[i]], collapse="")
      }
    
    return(list(y_loc = new_y_loc, x_loc = guard_details_input$x_loc, dir = ">", 
                input_map = input_map,
                dist_pos = (guard_details_input$dist_pos + total_moves_up),
                flag = FALSE))
    }
}

#Motion Right solver
motion_right <- function(guard_details_input, input_map, direction){
  motion <- c("Move","Stop")
  input_map_extract <- str_extract_all(input_map, boundary("character"))
  walls_along_route <- vector(mode = "list", length = length(guard_details_input$x_loc:(length(input_map_extract[[1]])-1)))
    
  for (i in 1:length(guard_details_input$x_loc:(length(input_map_extract[[1]])-1))){
    wall_x <- str_match_all(input_map_extract[[guard_details_input$y_loc]][guard_details_input$x_loc+i],wall)
      if (is_empty(wall_x)) {
          walls_along_route[[i]] <- "Move"
      } else if (!is_empty(wall_x)){
          walls_along_route[[i]] <- "Stop"
      }
    }

  find_all_stops <- str_match_all(walls_along_route,"Stop")
  
  if (is_empty(find_all_stops)){
      
      for (i in (guard_details_input$x_loc):(length(input_map_extract[[1]]))){
        input_map_extract[[guard_details_input$y_loc]][i] <- "X"
      }
      
      for (i in 1:length(input_map_extract)){
        input_map[[i]] <- paste(input_map_extract[[i]], collapse="")
      }
    
      return(list(dist_pos = (guard_details_input$dist_pos+length(find_all_stops)),
                  input_map = input_map, flag = TRUE))
      break
  } else if (!is_empty(find_all_stops)){
  
      first_stop <- min(which(lengths(find_all_stops)!=0))
      total_moves_right <- first_stop - 1
      new_x_loc <- guard_details_input$x_loc + total_moves_right
      
     #input_map_extract[[guard_details_input$y_loc]][guard_details_input$x_loc] <- "."
      input_map_extract[[guard_details_input$y_loc]][new_x_loc] <- "v"
      
      for (i in (guard_details_input$x_loc):(new_x_loc-1)){
        input_map_extract[[guard_details_input$y_loc]][i] <- "X"
      }
    
    
      for (i in 1:length(input_map_extract)){
        input_map[[i]] <- paste(input_map_extract[[i]], collapse="")
      }
    
    return(list(y_loc = guard_details_input$y_loc, x_loc = new_x_loc, dir = "v", 
                input_map = input_map,
                dist_pos = (guard_details_input$dist_pos + total_moves_right),
                flag = FALSE))
    }
}

#Motion Down solver
motion_down <- function(guard_details_input, input_map, direction){
  motion <- c("Move","Stop")
  input_map_extract <- str_extract_all(input_map, boundary("character"))
  walls_along_route <- vector(mode = "list", length = length((guard_details_input$y_loc+1):length(input_map)))

  for (i in ((guard_details_input$y_loc+1):length(input_map))){
    wall_x <- str_match_all(input_map_extract[[i]][guard_details_input$x_loc],wall)
      if (is_empty(wall_x)) {
          walls_along_route[[i]] <- "Move"
      } else if (!is_empty(wall_x)){
          walls_along_route[[i]] <- "Stop"
      }
    }

  find_all_stops <- str_match_all(walls_along_route,"Stop")
  
  if (is_empty(find_all_stops)){
      
      for (i in (guard_details_input$y_loc):(length(input_map))){
        input_map_extract[[i]][guard_details_input$x_loc] <- "X"
      }
      
      for (i in 1:length(input_map_extract)){
        input_map[[i]] <- paste(input_map_extract[[i]], collapse="")
      }
    
      return(list(dist_pos = (guard_details_input$dist_pos+length(find_all_stops)),
                  input_map = input_map, flag = TRUE))
      break
  } else if (!is_empty(find_all_stops)){
  
      first_stop <- min(which(lengths(find_all_stops)!=0))
      total_moves_down <-  first_stop - guard_details_input$y_loc - 1
      new_y_loc <- total_moves_down + guard_details_input$y_loc
      
      #input_map_extract[[guard_details_input$y_loc]][guard_details_input$x_loc] <- "."
      input_map_extract[[new_y_loc]][guard_details_input$x_loc] <- "<"
      
      for (i in (guard_details_input$y_loc):(new_y_loc-1)){
        input_map_extract[[i]][guard_details_input$x_loc] <- "X"
      }
    
      for (i in 1:length(input_map_extract)){
        input_map[[i]] <- paste(input_map_extract[[i]], collapse="")
      }
    
    return(list(y_loc = new_y_loc, x_loc = guard_details_input$x_loc, dir = "<", 
                input_map = input_map,
                dist_pos = (guard_details_input$dist_pos + total_moves_down),
                flag = FALSE))
    }
}

#Motion Left solver
motion_left <- function(guard_details_input, input_map, direction){
  motion <- c("Move","Stop")
  input_map_extract <- str_extract_all(input_map, boundary("character"))
  walls_along_route <- vector(mode = "list", length = guard_details_input$x_loc)
    
  for (i in 1:(guard_details_input$x_loc-1)){
    wall_x <- str_match_all(input_map_extract[[guard_details_input$y_loc]][i],wall)
      if (is_empty(wall_x)) {
          walls_along_route[[i]] <- "Move"
      } else if (!is_empty(wall_x)){
          walls_along_route[[i]] <- "Stop"
      }
    }

  find_all_stops <- str_match_all(walls_along_route,"Stop")
  
  if (is_empty(find_all_stops)){
    
      for (i in 1:(guard_details_input$x_loc)){
        input_map_extract[[guard_details_input$y_loc]][i] <- "X"
      }
    
      for (i in 1:length(input_map_extract)){
        input_map[[i]] <- paste(input_map_extract[[i]], collapse="")
      }
      return(list(dist_pos = (guard_details_input$dist_pos+length(find_all_stops)),
                  input_map = input_map, flag = TRUE))
      break
  } else if (!is_empty(find_all_stops)){
  
      first_stop <- max(which(lengths(find_all_stops)!=0))
      total_moves_left <- guard_details_input$x_loc - first_stop - 1
      new_x_loc <- guard_details_input$x_loc - total_moves_left
      
      #input_map_extract[[guard_details_input$y_loc]][guard_details_input$x_loc] <- "."
      input_map_extract[[guard_details_input$y_loc]][new_x_loc] <- "^"
      
      for (i in (new_x_loc+1):(guard_details_input$x_loc)){
        input_map_extract[[guard_details_input$y_loc]][i] <- "X"
      }
      
      for (i in 1:length(input_map_extract)){
        input_map[[i]] <- paste(input_map_extract[[i]], collapse="")
      }
    
    return(list(y_loc = guard_details_input$y_loc, x_loc = new_x_loc, dir = "^", 
                input_map = input_map,
                dist_pos = (guard_details_input$dist_pos + total_moves_left),
                flag = FALSE))
    }
}

start.time <- Sys.time()
while (isFALSE(off_map_flag)){
  guard_details <- find_guard_details(input_map, direction, dist_pos)
  
  if (guard_details$direction == "^"){
    up <- motion_up(guard_details,input_map,direction)
    
    input_map <- up$input_map
    dist_pos <- up$dist_pos
    off_map_flag <- up$flag
    
  } else if (guard_details$direction == "v"){
    down <- motion_down(guard_details,input_map,direction)
    
    input_map <- down$input_map
    dist_pos <- down$dist_pos
    off_map_flag <- down$flag
    
  } else if (guard_details$direction == "<"){
    left <- motion_left(guard_details,input_map,directions)
    
    input_map <- left$input_map
    dist_pos <- left$dist_pos
    off_map_flag <- left$flag
    
  } else if (guard_details$direction == ">"){
    right <- motion_right(guard_details,input_map,direction)
    
    input_map <- right$input_map
    dist_pos <- right$dist_pos
    off_map_flag <- right$flag
  }
  count <- count + 1
  print(paste("Count",count))
}

input_map_extract <- str_extract_all(input_map, boundary("character"))
distinct_pos <- 0
for (i in 1:length(input_map)){
    input_map_row <- str_match_all(input_map_extract[[i]],"X")
    distinct_pos <- distinct_pos + length(which(lengths(input_map_row)!=0))
}

pt1_solution <- distinct_pos
end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken
```

```{r main}

# Part 2
obs_input_map_extract <- str_extract_all(input_map, boundary("character"))
x_ids <- vector(mode = "list", length = length(input_map))

for (i in 1:length(input_map)){
    input_map_row <- str_match_all(input_map_extract[[i]],"X")
    x_ids[[i]] <- which(lengths(input_map_row)!=0)
    
}

alt_input_maps <- vector(mode = "list", length = 4967)
count <- 0
direction <- c("\\^","v","\\>","\\<")
dist_pos <- 1

for (i in 1:length(x_ids)){
  for (j in 1:length(x_ids[[1]])){
    
    if (!identical(x_ids[[i]], integer(0))){
      temp_map <- file_content
      temp_map_extract <- str_extract_all(temp_map, boundary("character"))
      temp_map_extract[[i]][x_ids[[i]][j]] <- "#"
      
      start_loc <- find_guard_details(temp_map,direction,dist_pos)
      temp_map_extract[[start_loc$y_loc]][start_loc$x_loc] <- start_loc$direction
      
      for (k in 1:length(temp_map_extract)){
        temp_map[[k]] <- paste(temp_map_extract[[k]], collapse="")
      }
    
    count <- count + 1
    alt_input_maps[[count]] <- temp_map
      
    }
     
  }  
}


start.time <- Sys.time()
obstruction <- vector(mode = "list", length = 4967)
inner_count <- 0
off_map_flag <- FALSE

for (i in 1:length(alt_input_maps)){
  input_map_ob <- alt_input_maps[[i]]
  #input_map_ob < file_content
  while (isFALSE(off_map_flag)){
    guard_details <- find_guard_details(input_map_ob, direction, dist_pos)
    
    if (guard_details$direction == "^"){
      up <- motion_up(guard_details,input_map_ob,direction)
      
      input_map_ob <- up$input_map
      dist_pos <- up$dist_pos
      off_map_flag <- up$flag
      
    } else if (guard_details$direction == "v"){
      down <- motion_down(guard_details,input_map_ob,direction)
      
      input_map_ob <- down$input_map
      dist_pos <- down$dist_pos
      off_map_flag <- down$flag
      
    } else if (guard_details$direction == "<"){
      left <- motion_left(guard_details,input_map_ob,directions)
      
      input_map_ob <- left$input_map
      dist_pos <- left$dist_pos
      off_map_flag <- left$flag
      
    } else if (guard_details$direction == ">"){
      right <- motion_right(guard_details,input_map_ob,direction)
      
      input_map_ob <- right$input_map
      dist_pos <- right$dist_pos
      off_map_flag <- right$flag
    }
    
    #inner_count <- inner_count + 1
    #print(paste("Count",inner_count))
    
    if (inner_count > 500){
      break
    }
  }
  
     
  if (inner_count > 500){
    obstruction[[i]] <- "Looped"
  } else if (!isFALSE(off_map_flag)){
    obstruction[[i]] <- "Not"
  }
  inner_count <- 0 

  print(paste("Alt Input",i))
  print(paste("Result",obstruction[[i]]))
}

end.time <- Sys.time()
time.taken <- end.time - start.time
time.taken


```
